"""
Rulebook tests for Aadhaar, PAN and certificates.

No real document data appears here. Aadhaar numbers are generated by computing
a valid Verhoeff check digit over an arbitrary payload, so the tests exercise
real arithmetic without embedding anybody's identity number in source control.
"""

from __future__ import annotations

from datetime import date, timedelta

import pytest

from app.rules.aadhaar import (
    is_valid_aadhaar,
    mask,
    validate_aadhaar,
    verhoeff_check_digit,
    verhoeff_checksum,
)
from app.rules.certificate import (
    find_number_word_phrases,
    validate_certificate,
    words_to_number,
)
from app.rules.pan import (
    HOLDER_TYPES,
    is_structurally_valid,
    surname_initial,
    validate_pan,
)
from app.schemas.document import ExtractedFields, FieldConfidence
from app.schemas.signals import SignalStatus


def make_aadhaar(payload: str = "23412341234") -> str:
    """Build a checksum-valid Aadhaar number from an 11-digit payload."""
    return payload + str(verhoeff_check_digit(payload))


def fields_with(**kwargs) -> ExtractedFields:
    f = ExtractedFields()
    for name, value in kwargs.items():
        setattr(f, name, FieldConfidence(value=value, raw=str(value), confidence=0.9))
    return f


# ---------------------------------------------------------------- Aadhaar --


class TestVerhoeff:
    def test_uidai_published_test_numbers_validate(self):
        for number in ("234123412346", "999999990019"):
            assert verhoeff_checksum(number) == 0

    def test_generated_check_digit_round_trips(self):
        for payload in ("23412341234", "48765432109", "99999999001"):
            assert verhoeff_checksum(make_aadhaar(payload)) == 0

    def test_catches_every_single_digit_error(self):
        """Verhoeff's guarantee, and the reason UIDAI chose it."""
        base = make_aadhaar()
        missed = [
            base[:i] + d + base[i + 1 :]
            for i in range(12)
            for d in "0123456789"
            if d != base[i] and verhoeff_checksum(base[:i] + d + base[i + 1 :]) == 0
        ]
        assert missed == []

    def test_catches_adjacent_transpositions(self):
        """
        The error a plain mod-10 checksum misses entirely, and the one people
        and OCR engines make most: swapping neighbouring digits.
        """
        base = make_aadhaar()
        missed = [
            i
            for i in range(11)
            if base[i] != base[i + 1]
            and verhoeff_checksum(base[:i] + base[i + 1] + base[i] + base[i + 2 :]) == 0
        ]
        assert missed == []

    def test_reserved_leading_digits_rejected(self):
        assert not is_valid_aadhaar("0" + make_aadhaar()[1:])
        assert not is_valid_aadhaar("1" + make_aadhaar()[1:])

    def test_wrong_length_rejected(self):
        assert not is_valid_aadhaar("12345678901")


class TestAadhaarPrivacy:
    def test_mask_reveals_only_last_four(self):
        assert mask("234123412346") == "XXXX XXXX 2346"

    def test_no_signal_ever_contains_the_full_number(self):
        """
        A verification tool must not be the place a national identity number
        leaks from. Reasons and evidence outlive the request in logs and API
        responses.
        """
        number = make_aadhaar()
        for sig in validate_aadhaar(None, fields_with(document_number=number)):
            assert number not in sig.reason
            assert number not in str(sig.evidence)


class TestAadhaarRules:
    def test_valid_number_passes(self):
        signals = validate_aadhaar(None, fields_with(document_number=make_aadhaar()))
        checksum = [s for s in signals if s.code == "aadhaar.checksum.valid"]
        assert checksum and checksum[0].status == SignalStatus.PASS

    def test_invalid_checksum_fails_critically(self):
        bad = make_aadhaar()[:-1] + str((int(make_aadhaar()[-1]) + 1) % 10)
        signals = validate_aadhaar(None, fields_with(document_number=bad))
        failed = [s for s in signals if s.code == "aadhaar.checksum.invalid"]
        assert failed and failed[0].severity.value == "critical"

    def test_reason_names_the_expected_check_digit(self):
        """A reviewer should be able to see the arithmetic, not just the verdict."""
        bad = make_aadhaar()[:-1] + str((int(make_aadhaar()[-1]) + 1) % 10)
        signals = validate_aadhaar(None, fields_with(document_number=bad))
        reason = next(s.reason for s in signals if s.code == "aadhaar.checksum.invalid")
        assert "requires" in reason

    def test_missing_number_blocks_without_accusing(self):
        signals = validate_aadhaar(None, ExtractedFields())
        assert signals[0].status == SignalStatus.ERROR
        assert signals[0].blocking is True

    def test_repeated_digits_flagged(self):
        signals = validate_aadhaar(None, fields_with(document_number="222222222222"))
        assert any(s.code == "aadhaar.number.low_entropy" for s in signals)

    def test_future_date_of_birth_blocks(self):
        tomorrow = date.today() + timedelta(days=1)
        signals = validate_aadhaar(
            None, fields_with(document_number=make_aadhaar(), date_of_birth=tomorrow)
        )
        assert any(s.code == "aadhaar.dob.future" and s.blocking for s in signals)


# -------------------------------------------------------------------- PAN --


class TestPANStructure:
    def test_valid_pan_accepted(self):
        assert is_structurally_valid("PQZPK6899H")

    @pytest.mark.parametrize(
        "value", ["PQZPK6899", "PQZP16899H", "PQZPK689H", "1QZPK6899H"]
    )
    def test_malformed_rejected(self, value):
        assert not is_structurally_valid(value)

    def test_unknown_holder_type_rejected(self):
        """Fourth character encodes the holder category and must be a real one."""
        assert "X" not in HOLDER_TYPES
        assert not is_structurally_valid("PQZXK6899H")


class TestPANSurnameCrossCheck:
    """
    The only redundancy a PAN card carries: the number's fifth character is the
    first letter of the surname, so the number and the printed name must agree.
    """

    def test_matching_surname_initial_passes(self):
        signals = validate_pan(
            None, fields_with(document_number="PQZPK6899H", full_name="PARTH KHODE")
        )
        assert any(s.code == "pan.surname_initial.match" for s in signals)

    def test_mismatched_surname_initial_fails(self):
        signals = validate_pan(
            None, fields_with(document_number="PQZPK6899H", full_name="PARTH SHARMA")
        )
        assert any(s.code == "pan.surname_initial.mismatch" for s in signals)

    def test_mismatch_is_not_reported_as_certain(self):
        """
        Surname-last is a convention, not a rule: mononyms and reordered names
        produce honest mismatches. Strong enough to escalate, not to conclude.
        """
        signals = validate_pan(
            None, fields_with(document_number="PQZPK6899H", full_name="PARTH SHARMA")
        )
        mismatch = next(s for s in signals if s.code == "pan.surname_initial.mismatch")
        assert mismatch.confidence < 0.8

    def test_honorifics_do_not_become_the_surname(self):
        assert surname_initial("SHRI PARTH KHODE") == "K"

    def test_missing_name_is_skip_not_failure(self):
        signals = validate_pan(None, fields_with(document_number="PQZPK6899H"))
        skipped = [s for s in signals if s.code == "pan.surname_initial.no_name"]
        assert skipped and skipped[0].status == SignalStatus.SKIP


class TestPANHonesty:
    def test_check_digit_is_reported_as_unverifiable(self):
        """
        The tenth character IS a check digit, but its algorithm was never
        published. Claiming to have verified it would be inventing evidence.
        """
        signals = validate_pan(None, fields_with(document_number="PQZPK6899H"))
        unverifiable = [s for s in signals if s.code == "pan.check_digit.unverifiable"]
        assert unverifiable and unverifiable[0].status == SignalStatus.SKIP


# ------------------------------------------------------------ Certificate --


class TestNumberWords:
    @pytest.mark.parametrize(
        "phrase,value",
        [
            ("SIXTY THREE", 63),
            ("NINETY", 90),
            ("ONE HUNDRED", 100),
            ("SEVENTEEN", 17),
            ("FOURTY FIVE", 45),  # common print error for 'forty'
        ],
    )
    def test_parsing(self, phrase, value):
        assert words_to_number(phrase) == value

    def test_consecutive_words_group_into_one_number(self):
        found = dict(find_number_word_phrases("TOTAL SIXTY THREE MARKS"))
        assert found.get("SIXTY THREE") == 63


class TestCertificateRules:
    def _marksheet(self, body: str) -> ExtractedFields:
        return fields_with(raw_text=body)

    def test_recognised_board_passes(self):
        signals = validate_certificate(
            None,
            self._marksheet("CENTRAL BOARD OF SECONDARY EDUCATION\nRoll No. 22645310\n2023"),
        )
        assert any(s.code == "certificate.issuer.identified" for s in signals)

    def test_unknown_issuer_blocks(self):
        signals = validate_certificate(None, self._marksheet("SOME RANDOM DOCUMENT\n2023"))
        issuer = next(s for s in signals if s.code == "certificate.issuer.unknown")
        assert issuer.blocking is True

    def test_total_matching_its_words_passes(self):
        signals = validate_certificate(
            None, self._marksheet("CBSE\nENGLISH CORE 301 043 020 063 SIXTY THREE C2")
        )
        assert any(s.code == "certificate.totals.match" for s in signals)

    def test_altered_digits_are_caught_by_the_words(self):
        """
        The forgery this rulebook exists to catch: the mark is raised in
        digits, and the words printed beside it are left behind.
        """
        signals = validate_certificate(
            None, self._marksheet("CBSE\nENGLISH CORE 301 093 020 093 SIXTY THREE C2")
        )
        assert any(s.code == "certificate.totals.mismatch" for s in signals)

    def test_mismatch_is_not_reported_as_certain(self):
        """Dense tables are where OCR makes most of its mistakes."""
        signals = validate_certificate(
            None, self._marksheet("CBSE\nENGLISH CORE 301 093 020 093 SIXTY THREE C2")
        )
        mismatch = next(s for s in signals if s.code == "certificate.totals.mismatch")
        assert mismatch.confidence < 0.8

    def test_future_examination_year_fails(self):
        future = date.today().year + 2
        signals = validate_certificate(None, self._marksheet(f"CBSE\nEXAMINATION {future}"))
        assert any(s.code == "certificate.year.future" for s in signals)

    def test_no_words_present_is_skip_not_pass(self):
        """
        Absence of the cross-check must not read as having passed it.
        """
        signals = validate_certificate(None, self._marksheet("CBSE\nRoll No. 22645310"))
        assert any(
            s.code == "certificate.totals.no_words" and s.status == SignalStatus.SKIP
            for s in signals
        )
