"""
Create the first administrator, and a signing key if there is none.

Solves the obvious chicken-and-egg problem: creating accounts needs the
'users:manage' permission, and nobody holds it until an account exists. This
runs against the database directly, and is the only path that does.

It deliberately does NOT invent a default password. A bootstrap that seeds
admin/admin is how a system ends up deployed with a known credential -- it
works, nobody revisits it, and the account survives into production. The
password is prompted for, or generated and printed once.

Usage:
    python scripts/bootstrap_admin.py
    python scripts/bootstrap_admin.py --username rajdeep --generate-password
"""

from __future__ import annotations

import argparse
import getpass
import os
import secrets
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BACKEND = REPO_ROOT / "backend"
sys.path.insert(0, str(BACKEND))

ENV_FILE = BACKEND / ".env"


def ensure_secret() -> str:
    """
    Make sure a JWT signing key exists, generating one into .env if not.

    Written to a file rather than printed as an instruction, because a key that
    has to be copied by hand is a key that ends up as "changeme" on the server
    that mattered.
    """
    from app.core.security import MIN_SECRET_LENGTH, generate_secret

    existing = os.environ.get("VERISHIELD_JWT_SECRET", "")
    if len(existing) >= MIN_SECRET_LENGTH:
        return "already set in the environment"

    text = ENV_FILE.read_text(encoding="utf-8") if ENV_FILE.exists() else ""
    for line in text.splitlines():
        if line.startswith("VERISHIELD_JWT_SECRET="):
            value = line.split("=", 1)[1].strip()
            if len(value) >= MIN_SECRET_LENGTH:
                os.environ["VERISHIELD_JWT_SECRET"] = value
                return f"already set in {ENV_FILE.name}"

    secret = generate_secret()
    with ENV_FILE.open("a", encoding="utf-8") as fh:
        fh.write(
            "\n# JWT signing key. Generated by scripts/bootstrap_admin.py.\n"
            "# Anyone holding this can mint valid tokens -- never commit it.\n"
            f"VERISHIELD_JWT_SECRET={secret}\n"
        )
    os.environ["VERISHIELD_JWT_SECRET"] = secret
    return f"generated and written to {ENV_FILE.name}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Create the first admin account.")
    parser.add_argument("--username", default="admin")
    parser.add_argument("--full-name", default="")
    parser.add_argument(
        "--generate-password",
        action="store_true",
        help="Generate a strong password and print it once instead of prompting.",
    )
    args = parser.parse_args()

    print(f"JWT signing key: {ensure_secret()}")

    from app.core.security import Role, password_problems
    from app.core.users import user_store

    if not user_store.available:
        print(f"\nCannot reach the user store: {user_store.error}")
        print("Start the data layer first:  docker compose up -d")
        return 1

    if user_store.get(args.username) is not None:
        print(f"\nUser {args.username!r} already exists. Nothing to do.")
        return 0

    existing_admins = [u for u in user_store.list_users() if u.role == Role.ADMIN]
    if existing_admins:
        print(f"\nAn admin already exists ({existing_admins[0].username}).")
        print("Create further accounts through POST /api/v1/auth/users.")
        return 0

    if args.generate_password:
        password = secrets.token_urlsafe(18)
        print(f"\nGenerated password: {password}")
        print("Copy it now -- it is not stored anywhere in readable form.")
    else:
        password = getpass.getpass("Choose a password (at least 12 characters): ")
        if password != getpass.getpass("Confirm: "):
            print("Passwords did not match.")
            return 1

    problems = password_problems(password)
    if problems:
        print(f"\nThat password {', and '.join(problems)}.")
        return 1

    user = user_store.create(args.username, password, Role.ADMIN, args.full_name)
    if user is None:
        print("\nCould not create the account.")
        return 1

    print(f"\nCreated admin {user.username!r}.")
    print("\nLog in with:")
    print("  curl -X POST http://localhost:8000/api/v1/auth/login \\")
    print(f"    -d 'username={user.username}&password=<the password>'")
    return 0


if __name__ == "__main__":
    sys.exit(main())
