"""
Measure how well VeriShield actually performs on your documents.

Two questions, answered separately because they need different data:

1. GENUINE documents (backend/data/datasets/raw/<type>/, folder name = truth).
   How often does the system trouble a real person about a real document?

   * **Classification accuracy**, with a confusion matrix. A wrong type is worse
     than no type, because the type selects the rulebook -- so misclassifications
     and UNKNOWNs are counted separately.
   * **Extraction rate** of the fields each rulebook depends on.
   * **Decision distribution.** On genuine documents every rejection is a false
     positive, and every manual review is friction.
   * **Why manual review happened.** The blocking and adverse signals behind
     each escalation, counted -- the only way to know which rule to fix to
     bring the review rate down without letting anything through.
   * **QR signature outcomes** on the documents whose QR could be read.
   * **Confidence calibration** and **timing per stage**.

2. FORGERIES (backend/data/datasets/generated/). Synthetic tampering of those
   same documents, each paired with its clean re-encoding.

   A forgery counts as CAUGHT only if its clean original was accepted and the
   forgery was not. Counting every non-accepted forgery as caught would credit
   the system for escalating forgeries of documents it escalated anyway -- a
   reverse side, an unreadable number -- which is not detecting anything.
   Pairs whose original was not accepted are reported as uninformative.

Every rate is printed with a Wilson 95% interval. Twenty-eight documents is a
small sample: "96%" on 28 means "somewhere around 82-99%", and a report that
drops the interval overstates what was measured.

What this still cannot tell you: the forgeries are generated by a script, not
made by people trying not to be caught. A high catch rate here is a floor on
what a careless forger faces, not a claim about a careful one.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import statistics
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BACKEND = REPO_ROOT / "backend"
sys.path.insert(0, str(BACKEND))

DATASETS = BACKEND / "data" / "datasets"
RAW = DATASETS / "raw"
GENERATED = DATASETS / "generated"
IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".heic", ".heif", ".webp"}

# Fields each rulebook needs before it can do anything meaningful.
REQUIRED_FIELDS: dict[str, list[str]] = {
    "aadhaar": ["document_number"],
    "pan": ["document_number", "full_name"],
    "certificate": ["raw_text"],
    "passport": ["document_number", "date_of_birth"],
}

TAMPERED_NAME = re.compile(r"^(?P<type>[a-z]+)_(?P<n>\d+)_(?P<op>[a-z_]+)\.\w+$")


# ------------------------------------------------------------------ helpers --


def wilson(hits: int, n: int, z: float = 1.96) -> tuple[float, float]:
    """95% interval for a proportion. Honest at small n, where p +/- 2se is not."""
    if n == 0:
        return 0.0, 0.0
    p = hits / n
    denominator = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / denominator
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / denominator
    return max(0.0, centre - half), min(1.0, centre + half)


def rate(hits: int, n: int) -> str:
    if n == 0:
        return "  n/a"
    low, high = wilson(hits, n)
    return f"{hits / n:>5.0%}  [{low:.0%}-{high:.0%}]"


def bar(value: float, width: int = 24) -> str:
    filled = int(round(value * width))
    return "#" * filled + "." * (width - filled)


def heading(title: str) -> None:
    print(f"\n{'=' * 72}\n{title}\n{'=' * 72}")


def collect_genuine() -> list[tuple[Path, str]]:
    found = []
    if not RAW.exists():
        return found
    for type_dir in sorted(RAW.iterdir()):
        if not type_dir.is_dir():
            continue
        for path in sorted(type_dir.iterdir()):
            if path.suffix.lower() in IMAGE_SUFFIXES:
                found.append((path, type_dir.name))
    return found


def collect_forgeries() -> list[dict]:
    """Each tampered image with the clean re-encoding it was made from."""
    pairs = []
    tampered_dir, clean_dir = GENERATED / "tampered", GENERATED / "clean"
    if not tampered_dir.exists():
        return pairs
    for path in sorted(tampered_dir.iterdir()):
        match = TAMPERED_NAME.match(path.name)
        if not match:
            continue
        clean = clean_dir / f"{match['type']}_{match['n']}_clean.jpg"
        if clean.exists():
            pairs.append(
                {"tampered": path, "clean": clean, "truth": match["type"], "op": match["op"]}
            )
    return pairs


def summarise(analysis) -> dict:
    """The parts of an assessment the metrics use. No field values, no names."""
    risk = analysis.risk
    adverse = sorted(
        {s.code for s in analysis.signals if s.status.value in ("fail", "error", "warn")}
    )
    qr = next(
        (s.code.rsplit(".", 1)[-1] for s in analysis.signals
         if s.code.startswith("aadhaar.qr.signature.")),
        None,
    )
    return {
        "predicted": analysis.document_type.value,
        "side": analysis.side.value,
        "type_confidence": round(analysis.type_confidence, 3),
        "risk": risk.score,
        "decision": risk.decision.value,
        "evidence_confidence": risk.confidence,
        "blocking_codes": list(risk.blocking_codes),
        "adverse_codes": adverse,
        "qr_signature": qr,
    }


# --------------------------------------------------------------------- main --


def main() -> int:
    parser = argparse.ArgumentParser(description="Evaluate VeriShield on labelled documents.")
    parser.add_argument("--limit", type=int, default=None, help="Only evaluate N genuine documents.")
    parser.add_argument("--no-face", action="store_true", help="Skip face detection (much faster).")
    parser.add_argument("--no-forgeries", action="store_true", help="Skip the synthetic forgery set.")
    parser.add_argument("--json", type=str, default=None, help="Write results to this path.")
    args = parser.parse_args()

    import logging

    logging.disable(logging.WARNING)

    from app.pipeline.orchestrator import analyze_document
    from app.pipeline.stages.face import NullFaceProvider
    from app.registry.authority import SyntheticRegistry

    registry = SyntheticRegistry.from_file(BACKEND / "data" / "synthetic_registry.json")
    face_provider = NullFaceProvider() if args.no_face else None

    def assess(path: Path):
        return analyze_document(
            path.read_bytes(), path.name, registry=registry, face_provider=face_provider
        )

    previous = None
    if args.json and Path(args.json).exists():
        try:
            previous = json.loads(Path(args.json).read_text(encoding="utf-8"))
        except (ValueError, OSError):
            previous = None

    samples = collect_genuine()
    if args.limit:
        samples = samples[: args.limit]
    if not samples:
        print(f"No documents found under {RAW}.")
        print("Put images in raw/<type>/ -- the folder name is the ground-truth label.")
        return 1

    print(f"Evaluating {len(samples)} genuine documents from {RAW}\n")

    confusion: dict[str, Counter] = defaultdict(Counter)
    sides = Counter()
    decisions = Counter()
    extraction: dict[str, list[bool]] = defaultdict(list)
    timings: dict[str, list[float]] = defaultdict(list)
    confidence_buckets: dict[str, list[bool]] = defaultdict(list)
    review_blocking = Counter()
    review_adverse = Counter()
    qr_outcomes = Counter()
    rejects: list[tuple[str, str, str]] = []
    rows = []

    started = time.perf_counter()
    for i, (path, truth) in enumerate(samples, 1):
        analysis = assess(path)
        row = summarise(analysis)

        predicted = row["predicted"]
        confusion[truth][predicted] += 1
        sides[row["side"]] += 1
        decisions[row["decision"]] += 1

        correct = predicted == truth
        # Only the front carries the fields a rulebook needs; scoring
        # extraction on reverse sides would penalise the system for correctly
        # reporting that a back has no identity data on it.
        if correct and row["side"] == "front":
            for field in REQUIRED_FIELDS.get(truth, []):
                extraction[f"{truth}.{field}"].append(getattr(analysis.fields, field).present)

        for stage, ms in analysis.processing_ms.items():
            timings[stage].append(ms)

        band = (
            "high (>=0.8)" if row["evidence_confidence"] >= 0.8
            else "medium (0.5-0.8)" if row["evidence_confidence"] >= 0.5
            else "low (<0.5)"
        )
        confidence_buckets[band].append(correct)

        if row["decision"] == "manual_review":
            review_blocking.update(row["blocking_codes"])
            review_adverse.update(row["adverse_codes"])
        if row["qr_signature"]:
            qr_outcomes[row["qr_signature"]] += 1
        if row["decision"] == "reject":
            reason = analysis.risk.top_reasons[0] if analysis.risk.top_reasons else ""
            rejects.append((path.name, truth, reason))

        rows.append({"file": path.name, "truth": truth, "correct": correct, **row})
        if i % 10 == 0 or i == len(samples):
            print(f"  {i}/{len(samples)}")

    genuine_elapsed = time.perf_counter() - started
    n = len(samples)

    # ---- classification -------------------------------------------------
    heading("GENUINE -- CLASSIFICATION")
    total = correct_total = 0
    for truth in sorted(confusion):
        counts = confusion[truth]
        count = sum(counts.values())
        hits = counts.get(truth, 0)
        total += count
        correct_total += hits
        print(f"  {truth:<14} {hits:>3}/{count:<3} {bar(hits / count)}  {rate(hits, count)}")
        for other, v in sorted(((k, v) for k, v in counts.items() if k != truth), key=lambda kv: -kv[1]):
            # UNKNOWN and a wrong type are different failures: one declines to
            # answer, the other answers wrongly and applies the wrong rules.
            kind = "declined" if other == "unknown" else "MISCLASSIFIED"
            print(f"                    -> {v} {kind} as {other}")
    print(f"\n  overall: {correct_total}/{total}  {rate(correct_total, total)}")
    print(f"  sides detected: {dict(sides)}")

    # ---- extraction -----------------------------------------------------
    heading("GENUINE -- FIELD EXTRACTION (fronts of correctly typed documents)")
    for key in sorted(extraction) or []:
        values = extraction[key]
        print(f"  {key:<28} {sum(values):>3}/{len(values):<3} {rate(sum(values), len(values))}")
    if not extraction:
        print("  nothing to measure")

    # ---- decisions ------------------------------------------------------
    heading("GENUINE -- DECISIONS")
    for decision in ("accept", "manual_review", "reject"):
        count = decisions.get(decision, 0)
        print(f"  {decision:<16} {count:>3}/{n:<3} {bar(count / n)}  {rate(count, n)}")
    print("\n  Every document here is presumed genuine: each 'reject' is a false")
    print("  positive, and each 'manual_review' is a person asked to look.")
    if rejects:
        print(f"\n  {len(rejects)} rejection(s) to investigate:")
        for name, truth, reason in rejects[:10]:
            print(f"    {name} ({truth}): {reason[:88]}")
    else:
        print("\n  No false rejections.")

    # ---- why manual review ---------------------------------------------
    heading("GENUINE -- WHY DOCUMENTS WENT TO MANUAL REVIEW")
    reviewed = decisions.get("manual_review", 0)
    if reviewed:
        print(f"  {reviewed} document(s). Blocking findings (each alone withholds acceptance):")
        for code, count in review_blocking.most_common(8):
            print(f"    {count:>3}x  {code}")
        print("\n  Adverse signals present (fail / error / warn):")
        for code, count in review_adverse.most_common(8):
            print(f"    {count:>3}x  {code}")
    else:
        print("  none")

    # ---- QR signatures --------------------------------------------------
    heading("GENUINE -- AADHAAR QR SIGNATURE")
    if qr_outcomes:
        for outcome, count in qr_outcomes.most_common():
            print(f"  {outcome:<14} {count}")
        print("\n  'invalid' on a genuine document would mean a wrong pinned key --")
        print("  it should never appear here.")
    else:
        print("  no QR was read from any genuine document")

    # ---- confidence calibration ----------------------------------------
    heading("GENUINE -- CONFIDENCE CALIBRATION")
    print(f"  {'confidence band':<20} {'n':>4}  classified correctly")
    for band in ("high (>=0.8)", "medium (0.5-0.8)", "low (<0.5)"):
        values = confidence_buckets.get(band, [])
        if values:
            print(f"  {band:<20} {len(values):>4}  {rate(sum(values), len(values))}")
    print("\n  Useful calibration means the high band scores better than the low one.")

    # ---- timing ---------------------------------------------------------
    heading("TIMING (milliseconds per genuine document)")
    print(f"  {'stage':<12} {'median':>9} {'mean':>9} {'max':>9}")
    for stage in sorted(timings, key=lambda s: -statistics.mean(timings[s])):
        values = timings[stage]
        print(f"  {stage:<12} {statistics.median(values):>9.0f} "
              f"{statistics.mean(values):>9.0f} {max(values):>9.0f}")
    print(f"\n  {genuine_elapsed:.1f}s for {n} documents ({genuine_elapsed / n:.1f}s each)")

    # ---- forgeries ------------------------------------------------------
    forgery_report = None
    pairs = [] if args.no_forgeries else collect_forgeries()
    if pairs:
        heading(f"FORGERIES -- {len(pairs)} synthetic, each paired with its clean original")
        started = time.perf_counter()
        clean_cache: dict[Path, dict] = {}
        by_op: dict[str, dict] = defaultdict(
            lambda: {"pairs": 0, "informative": 0, "caught": 0, "missed": 0,
                     "caught_by": Counter(), "tampered_accepted": 0}
        )
        forgery_rows = []
        for i, pair in enumerate(pairs, 1):
            if pair["clean"] not in clean_cache:
                clean_cache[pair["clean"]] = summarise(assess(pair["clean"]))
            clean = clean_cache[pair["clean"]]
            forged = summarise(assess(pair["tampered"]))

            stats = by_op[pair["op"]]
            stats["pairs"] += 1
            stats["tampered_accepted"] += forged["decision"] == "accept"
            outcome = "uninformative"
            if clean["decision"] == "accept":
                stats["informative"] += 1
                if forged["decision"] == "accept":
                    stats["missed"] += 1
                    outcome = "missed"
                else:
                    stats["caught"] += 1
                    outcome = "caught"
                    new = set(forged["adverse_codes"]) - set(clean["adverse_codes"])
                    stats["caught_by"].update(new or {"(same signals, higher score)"})
            forgery_rows.append({
                "file": pair["tampered"].name, "op": pair["op"], "truth": pair["truth"],
                "clean_decision": clean["decision"], "forged_decision": forged["decision"],
                "outcome": outcome,
                "new_adverse_codes": sorted(set(forged["adverse_codes"]) - set(clean["adverse_codes"])),
            })
            if i % 20 == 0 or i == len(pairs):
                print(f"  {i}/{len(pairs)}")

        print(f"\n  {'forgery':<24} {'pairs':>5} {'usable':>6}  {'caught':>22}  {'missed':>6}")
        totals = Counter()
        for op in sorted(by_op):
            s = by_op[op]
            totals.update({k: s[k] for k in ("pairs", "informative", "caught", "missed", "tampered_accepted")})
            print(f"  {op:<24} {s['pairs']:>5} {s['informative']:>6}  "
                  f"{s['caught']:>3} {rate(s['caught'], s['informative']):>18}  {s['missed']:>6}")
        print(f"  {'ALL':<24} {totals['pairs']:>5} {totals['informative']:>6}  "
              f"{totals['caught']:>3} {rate(totals['caught'], totals['informative']):>18}  "
              f"{totals['missed']:>6}")

        print("\n  What caught them (signals new in the forgery, absent from its original):")
        caught_by = Counter()
        for s in by_op.values():
            caught_by.update(s["caught_by"])
        for code, count in caught_by.most_common(8):
            print(f"    {count:>3}x  {code}")
        if not caught_by:
            print("    nothing")

        print(f"\n  Forgeries auto-ACCEPTED outright: {totals['tampered_accepted']}/{totals['pairs']}"
              f"  {rate(totals['tampered_accepted'], totals['pairs'])}")
        print("  'usable' pairs are those whose clean original was accepted; only there")
        print("  does a non-accept show the tampering was noticed.")
        print(f"\n  {time.perf_counter() - started:.1f}s")

        forgery_report = {
            "pairs": totals["pairs"],
            "informative_pairs": totals["informative"],
            "caught": totals["caught"],
            "missed": totals["missed"],
            "catch_rate": totals["caught"] / totals["informative"] if totals["informative"] else None,
            "catch_rate_ci95": wilson(totals["caught"], totals["informative"]),
            "auto_accepted": totals["tampered_accepted"],
            "by_operation": {
                op: {k: (dict(v) if isinstance(v, Counter) else v) for k, v in s.items()}
                for op, s in sorted(by_op.items())
            },
            "documents": forgery_rows,
        }

    # ---- against the previous run ---------------------------------------
    if previous:
        heading("AGAINST THE PREVIOUS RUN")
        before_acc = previous.get("classification_accuracy")
        if before_acc is not None:
            print(f"  classification  {before_acc:.1%} -> {correct_total / total:.1%}")
        before = previous.get("decisions", {})
        for decision in ("accept", "manual_review", "reject"):
            print(f"  {decision:<15} {before.get(decision, 0):>3} -> {decisions.get(decision, 0):<3}")

    if args.json:
        report = {
            "documents": rows,
            "classification_accuracy": correct_total / total,
            "classification_accuracy_ci95": wilson(correct_total, total),
            "decisions": dict(decisions),
            "decision_rates_ci95": {d: wilson(decisions.get(d, 0), n) for d in ("accept", "manual_review", "reject")},
            "manual_review_blocking": dict(review_blocking.most_common()),
            "manual_review_adverse": dict(review_adverse.most_common()),
            "qr_signature": dict(qr_outcomes),
            "elapsed_seconds": round(genuine_elapsed, 2),
        }
        if forgery_report:
            report["forgeries"] = forgery_report
        Path(args.json).write_text(json.dumps(report, indent=2), encoding="utf-8")
        print(f"\n  written to {args.json}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
